// 弹窗类型
export const COMMON_MODAL = 'COMMON_MODAL';
export const LIVE_SHARE_MODAL = 'LIVE_SHARE_MODAL';
export const UPLOAD_MODAL = 'UPLOAD_MODAL';
export const LIVE_PACKAGE_DOWNLOAD = 'LIVE_PACKAGE_DOWNLOAD';
export const GENERATE_DOWNLOAD_LINK = 'GENERATE_DOWNLOAD_LINK';
export const PERFECTLY_CLEAR_MODAL = 'PERFECTLY_CLEAR_MODAL';
export const FORMULATE_MODAL = 'FORMULATE_MODAL';
export const STYLE_MODAL = 'STYLE_MODAL';
export const CAMERAMAN_MODAL = 'CAMERAMAN_MODAL';
export const IAMGE_MODAL = 'IAMGE_MODAL';
export const DIFFERENT_MODAL = 'DIFFERENT_MODAL';
export const DAYLIMIT15_MODAL = 'DAYLIMIT15_MODAL';
export const AI_PHOTO_STATE_CHECK = 'AI_PHOTO_STATE_CHECK';
export const MOVE_MODAL = 'MOVE_MODAL';
export const AGAIN_PRINT_WATERMARK_MODAL = 'AGAIN_PRINT_WATERMARK_MODAL';
export const LIVE_CONFIRM_MODAL = 'LIVE_CONFIRM_MODAL';
