export const HIDE_SPLASH_SCREEN = 'HIDE_SPLASH_SCREEN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_LOADING_INFO = 'GET_LOADING_INFO';
export const SHOW_SPLASH_SCREEN = 'SHOW_SPLASH_SCREEN';
