export const SHARE_QRCODE_MODAL = 'SHARE_QRCODE_MODAL';
export const IMAGE_VIEWER_MODAL = 'IMAGE_VIEWER_MODAL';
export const UPLOAD_AI_MAPPING_DRAWER = 'UPLOAD_AI_MAPPING_DRAWER';
export const CLAUSE_DRAWER = 'CLAUSE_DRAWER';
export const AVATAR_SEARCH_DRAWER = 'AVATAR_SEARCH_DRAWER';
export const WATERMARK_TIP_MODAL = 'WATERMARK_TIP_MODAL';
export const CUSTOM_FORM_MODAL = 'CUSTOM_FORM_MODAL';
