const data = [
  {
    enc_album_content_rel_id: 'lSwocAJS9UQ%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'X0nPrbQGxMKRKq9NsvQ2QA%3D%3D',
    content_name: '5无翻转无角度.jpg',
    suffix: 'jpg',
    content_size: 1686179,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'X0nPrbQGxMKRKq9NsvQ2QA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '866a1cd0-4ff1-450d-b0ba-aba44c966023',
    create_time: 1693295426000,
    like_count: 0,
    shot_time: 1506236806000,
    width: 1333,
    height: 2000,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'FVpY3ws9OU6VK319CqGOQg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'FVpY3ws9OU6VK319CqGOQg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'xZGGKNmZwbI%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'dOWHICzf7ubN8IyECkO%2Ffw%3D%3D',
    content_name: '49(1).jpg',
    suffix: 'jpg',
    content_size: 387100,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'dOWHICzf7ubN8IyECkO%2Ffw%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '3b86ac61-7f33-4614-9209-012ba006245e',
    create_time: 1692956583000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 899,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: null,
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'dOWHICzf7ubN8IyECkO%2Ffw%3D%3D'
  },
  {
    enc_album_content_rel_id: 'DxV8Y4ikVWg%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq44fFCoX6Qk%2BJA%3D%3D',
    content_name: '48(1).jpg',
    suffix: 'jpg',
    content_size: 210763,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq44fFCoX6Qk%2BJA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '3270fc6d-773b-4782-b1c6-40f3a625c7cd',
    create_time: 1692956582000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 777,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: null,
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'rUL5D8cYq44fFCoX6Qk%2BJA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'oN78r0IRRMg%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq46PzRvU4vY1wg%3D%3D',
    content_name: '49(1).jpg',
    suffix: 'jpg',
    content_size: 387100,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq46PzRvU4vY1wg%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'f3bb6412-e430-489e-ac5d-a428b1dd3fcb',
    create_time: 1692955907000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 899,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNzOd%2B5%2FUCFWtg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNzOd%2B5%2FUCFWtg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'ScqM5hJembw%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq46RKq9NsvQ2QA%3D%3D',
    content_name: '40(1).jpg',
    suffix: 'jpg',
    content_size: 226165,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq46RKq9NsvQ2QA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'f763c45d-e641-4dcd-9f7a-eade1ecf6ed6',
    create_time: 1692955907000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 801,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNzUrM4PT%2Bn4KQ%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNzUrM4PT%2Bn4KQ%3D%3D'
  },
  {
    enc_album_content_rel_id: 'gReiw3Pb%2Bu0%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq46yLA32hiDOmA%3D%3D',
    content_name: '47(1).jpg',
    suffix: 'jpg',
    content_size: 233311,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq46yLA32hiDOmA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'c2ff4c85-e05c-4b4b-812a-f75765d78d59',
    create_time: 1692955907000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 798,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNyoL1CI6QQfYA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNyoL1CI6QQfYA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'ljZMVGFHG4Y%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq45yAyuJg00KhA%3D%3D',
    content_name: '48(1).jpg',
    suffix: 'jpg',
    content_size: 210763,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq45yAyuJg00KhA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'b9e31bb3-a44e-4c04-997c-459d1af2b7e3',
    create_time: 1692955907000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 777,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNzU%2FoSL1527pg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNzU%2FoSL1527pg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'Bhk3UMDPnfM%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq44w5QALr6Rqfw%3D%3D',
    content_name: '49(1).jpg',
    suffix: 'jpg',
    content_size: 387100,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq44w5QALr6Rqfw%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '8b5fac1c-887e-4647-b0d4-5406037669c2',
    create_time: 1692955727000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 899,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNxCn%2BRt%2BFqGZg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNxCn%2BRt%2BFqGZg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'whuOZxI2qX8%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq455Zq0i5Z2e8Q%3D%3D',
    content_name: '48(1).jpg',
    suffix: 'jpg',
    content_size: 210763,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq455Zq0i5Z2e8Q%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'bee95254-e832-4e20-bfc7-555b5954e35e',
    create_time: 1692955726000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 777,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNwzxrA8e5eFSw%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNwzxrA8e5eFSw%3D%3D'
  },
  {
    enc_album_content_rel_id: 'XvTgppR6C8Y%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq4715q3jWecC7g%3D%3D',
    content_name: '47(1).jpg',
    suffix: 'jpg',
    content_size: 233311,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq4715q3jWecC7g%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '47c2be12-1569-4dcc-8bca-fed33cc0cd12',
    create_time: 1692955726000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 798,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNxQ4yIzDFOfwQ%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNxQ4yIzDFOfwQ%3D%3D'
  },
  {
    enc_album_content_rel_id: 'Op%2FDszuKCl8%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'HYzeUZ3fN%2BUfFCoX6Qk%2BJA%3D%3D',
    content_name: '47(1).jpg',
    suffix: 'jpg',
    content_size: 233311,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'HYzeUZ3fN%2BUfFCoX6Qk%2BJA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'd2576377-1680-45f7-9c35-670d289bc723',
    create_time: 1692953739000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 798,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNz5Bx13ugekQg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNz5Bx13ugekQg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'L8A0GeF2HqU%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq44c9xiorEzQyg%3D%3D',
    content_name: '49(1).jpg',
    suffix: 'jpg',
    content_size: 387100,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq44c9xiorEzQyg%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'ec0e8c46-1ed7-4e99-87ab-04a77ae1bbd6',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 899,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNzRPxZKpfcesw%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNzRPxZKpfcesw%3D%3D'
  },
  {
    enc_album_content_rel_id: 'D%2F35%2FPtzmsc%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'HYzeUZ3fN%2BWPzRvU4vY1wg%3D%3D',
    content_name: '46.jpg',
    suffix: 'jpg',
    content_size: 71252,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'HYzeUZ3fN%2BWPzRvU4vY1wg%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '59c61455-444e-4811-a770-1695950e57d3',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 800,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNyyDFs00CMirA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNyyDFs00CMirA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'V4gvDV3uAGc%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'HYzeUZ3fN%2BWyLA32hiDOmA%3D%3D',
    content_name: '41.jpg',
    suffix: 'jpg',
    content_size: 115889,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'HYzeUZ3fN%2BWyLA32hiDOmA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '89e85edd-a52e-405f-a801-e5aec774d55c',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 754,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNw9LOiuiLyYSA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNw9LOiuiLyYSA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'qiyRMy1cmCU%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'rUL5D8cYq47N8IyECkO%2Ffw%3D%3D',
    content_name: '48(1).jpg',
    suffix: 'jpg',
    content_size: 210763,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'rUL5D8cYq47N8IyECkO%2Ffw%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '01f9919c-93a7-4011-a9b2-c773f9612ca2',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 777,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNxolkTBMQ%2BY9g%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNxolkTBMQ%2BY9g%3D%3D'
  },
  {
    enc_album_content_rel_id: '4gVhP7ALTPU%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'HYzeUZ3fN%2BWRKq9NsvQ2QA%3D%3D',
    content_name: '40(1).jpg',
    suffix: 'jpg',
    content_size: 226165,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'HYzeUZ3fN%2BWRKq9NsvQ2QA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '149b28cc-6f2f-4ecd-ad63-ffd4f23f55d7',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 801,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNwYj3oNlBVNoA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNwYj3oNlBVNoA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'LbKbGUrMxb0%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'HYzeUZ3fN%2BVyAyuJg00KhA%3D%3D',
    content_name: '42(1).jpg',
    suffix: 'jpg',
    content_size: 216560,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'HYzeUZ3fN%2BVyAyuJg00KhA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '86226591-71c8-430b-9cbc-cbc3a892b499',
    create_time: 1692953735000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 1033,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'mAk3l2htdNz%2BBDzW0zl2Rg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'mAk3l2htdNz%2BBDzW0zl2Rg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'gUutHJVRZn8%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'FbyJAm%2BpobByAyuJg00KhA%3D%3D',
    content_name: '47(1).jpg',
    suffix: 'jpg',
    content_size: 233311,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'FbyJAm%2BpobByAyuJg00KhA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '6222ba61-97e1-48a1-a118-77ab08c2c0f4',
    create_time: 1692947740000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 798,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'KxOk0pps56SjcnCcoYdVaA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'KxOk0pps56SjcnCcoYdVaA%3D%3D'
  },
  {
    enc_album_content_rel_id: '4qm8r9f4MNU%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'FbyJAm%2BpobCRKq9NsvQ2QA%3D%3D',
    content_name: '45.jpg',
    suffix: 'jpg',
    content_size: 160020,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'FbyJAm%2BpobCRKq9NsvQ2QA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'b276f619-5a6a-4210-9ab5-366ec642ad6a',
    create_time: 1692947740000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 800,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'KxOk0pps56RUiH7OaFK4sA%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'KxOk0pps56RUiH7OaFK4sA%3D%3D'
  },
  {
    enc_album_content_rel_id: 'T7gM%2Fa35ipQ%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'FbyJAm%2BpobCyLA32hiDOmA%3D%3D',
    content_name: '46.jpg',
    suffix: 'jpg',
    content_size: 71252,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'FbyJAm%2BpobCyLA32hiDOmA%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: 'd04df388-0284-43d8-bc9c-f3ade886f305',
    create_time: 1692947740000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 800,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'KxOk0pps56Te8lXf%2BL3oSg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'KxOk0pps56Te8lXf%2BL3oSg%3D%3D'
  },
  {
    enc_album_content_rel_id: 'vyGOpmJ3u3g%3D',
    album_id: 55,
    enc_album_id: null,
    resolution_type: 2,
    content_type: 1,
    enc_content_id: 'FbyJAm%2BpobAw5QALr6Rqfw%3D%3D',
    content_name: '44.jpg',
    suffix: 'jpg',
    content_size: 152850,
    content_status: 1,
    correct_enable: false,
    client_show: true,
    correct_enc_content_id: 'FbyJAm%2BpobAw5QALr6Rqfw%3D%3D',
    correct_status: 0,
    correct_content_source: '',
    camera_identifier: '1',
    content_uuid: '1da5def1-b517-400a-bc72-400eeb12f5c0',
    create_time: 1692947740000,
    like_count: 0,
    shot_time: 0,
    width: 1200,
    height: 800,
    orientation: 1,
    watermark_set_status: null,
    watermark_enc_content_id: 'KxOk0pps56Svzxq5GBqvQg%3D%3D',
    pho_customer_id: null,
    add_source: null,
    add_method: null,
    show_enc_content_id: 'KxOk0pps56Svzxq5GBqvQg%3D%3D'
  }
];

export default data;

// {
//   "Make": "Canon",
//   "Model": "Canon EOS 6D",
//   "XResolution": 240,
//   "YResolution": 240,
//   "ResolutionUnit": 2,
//   "Software": "Adobe Photoshop Lightroom Classic 11.5 (Macintosh)",
//   "DateTime": "2023:07:07 10:50:59",
//   "ExifIFDPointer": 12118,
//   "ExposureTime": 0.004,
//   "FNumber": 2.8,
//   "ExposureProgram": "Manual",
//   "ISOSpeedRatings": 100,
//   "undefined": "000082e883",
//   "ExifVersion": "0231",
//   "DateTimeOriginal": "2000:01:01 00:00:51",
//   "DateTimeDigitized": "2000:01:01 00:00:51",
//   "ShutterSpeedValue": 7.965784,
//   "ApertureValue": 2.970854,
//   "ExposureBias": 0,
//   "MaxApertureValue": 3,
//   "MeteringMode": "Pattern",
//   "Flash": "Flash did not fire, compulsory flash mode",
//   "FocalLength": 200,
//   "SubsecTimeOriginal": "94",
//   "SubsecTimeDigitized": "94",
//   "ColorSpace": 1,
//   "FocalPlaneXResolution": 1520,
//   "FocalPlaneYResolution": 1520,
//   "FocalPlaneResolutionUnit": 3,
//   "CustomRendered": "Normal process",
//   "ExposureMode": 1,
//   "WhiteBalance": "Auto white balance",
//   "SceneCaptureType": "Standard",
//   "thumbnail": {
//       "Compression": 6,
//       "XResolution": 72,
//       "YResolution": 72,
//       "ResolutionUnit": 2,
//       "JpegIFOffset": 8,
//       "JpegIFByteCount": 12110,
//       "blob": {}
//   }
// }
