export const UPDATE_NAVBAR_ITEMS = 'UPDATE_NAVBAR_ITEMS';
export const CLEAR_NAVBAR_ITEMS = 'CLEAR_NAVBAR_ITEMS';
export const SET_NAVBAR_LABTYPE = 'SET_NAVBAR_LABTYPE';
export const SET_NAVBAR_SUBSCRIPTION = 'SET_NAVBAR_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION';
