export const PRODUCT_INFO_MODAL = 'PRODUCT_INFO_MODAL';
export const MANAGER_OPTIONS_MODAL = 'MANAGER_OPTIONS_MODAL';
export const APPLY_BULK_MARKUP_MODAL = 'APPLY_BULK_MARKUP_MODAL';
// products
export const ADD_PRICE_SHEET_MODAL = 'ADD_PRICE_SHEET_MODAL';
export const PRICE_SHEET_SETTING = 'PRICE_SHEET_SETTING';
export const ASSIGN_TO_COLLECTIONS = 'ASSIGN_TO_COLLECTIONS';
export const DOUBLE_CHECK_ASSIGN = 'DOUBLE_CHECK_ASSIGN';
//taxes
export const ADD_TAXES_MODAL = 'ADD_TAXES_MODAL';
//setting
export const SETUP_PAYPAL_MODAL = 'SETUP_PAYPAL_MODAL';
// ORDER
export const ADD_COST_MODAL = 'ADD_COST_MODAL';
export const SHOW_DISCOUNT_MODAL = 'SHOW_DISCOUNT_MODAL';
export const ADD_SHIPPING_MODAL = 'ADD_SHIPPING_MODAL';
// Shipping
export const SETUP_SHIPPING_MODAL = 'SETUP_SHIPPING_MODAL';
export const COMMON_MODAL = 'COMMON_MODAL';
export const TRACK_INFO_MODAL = 'TRACK_INFO_MODAL';
export const UPLOAD_MODAL = 'UPLOAD_MODAL';
export const EDIT_PRODUCT_OPTIONS = 'EDIT_PRODUCT_OPTIONS';
export const MANAGE_OPTIONS_MODAL = 'MANAGE_OPTIONS_MODAL';
export const DOWNLOADMODAL = 'DOWNLOADMODAL';
export const SEND_PHOTO_DOWNLOADS_MODAL = 'SEND_PHOTO_DOWNLOADS_MODAL';
export const SETUP_STRIPE_MODAL = 'SETUP_STRIPE_MODAL';

// coupon
export const COUPON_FORM_MODAL = 'COUPON_FORM_MODAL';
export const COUPON_ADDPRODUCT_MODAL = 'COUPON_ADDPRODUCT_MODAL';
