const COLLECTION_DETAIL = 'COLLECTION_DETAIL';

// collection -> detail -> photos
export const RESET_COLLECTION_DETAIL = 'RESET_COLLECTION_DETAIL';
export const SHOW_IMAGE_NAME = `${COLLECTION_DETAIL}/SHOW_IMAGE_NAME`;
export const CHANGE_SELECTION = `${COLLECTION_DETAIL}/CHANGE_SELECTION`;
export const SELECT_ALL_IMG = `${COLLECTION_DETAIL}/SELECT_ALL_IMG`;
export const CLEAR_SELECTION = `${COLLECTION_DETAIL}/CLEAR_SELECTION`;
export const UPDATE_COVER = `${COLLECTION_DETAIL}/UPDATE_COVER`;
export const RENAME_IMG_NAME = `${COLLECTION_DETAIL}/RENAME_IMG_NAME`;
export const DELETE_IMAGE = `${COLLECTION_DETAIL}/DELETE_IMAGE`;
export const SHOW_IMAGE_VIEWER = `${COLLECTION_DETAIL}/SHOW_IMAGE_VIEWER`;
export const HIDE_IMAGE_VIEWER = `${COLLECTION_DETAIL}/HIDE_IMAGE_VIEWER`;
export const UPDATE_WATERMARK_LIST = `${COLLECTION_DETAIL}/UPDATE_WATERMARK_LIST`;
export const APPLY_WATERMARK = `${COLLECTION_DETAIL}/APPLY_WATERMARK`;
export const CHANGE_CURRENT_SET_UID = `${COLLECTION_DETAIL}/CHANGE_CURRENT_SET_UID`;
export const MOVE_IMAGE = `${COLLECTION_DETAIL}/MOVE_IMAGE`;
export const COPY_IMAGE = `${COLLECTION_DETAIL}/COPY_IMAGE`;
export const ORDERING_SET = `${COLLECTION_DETAIL}/ORDERING_SET`;
export const SET_DETAIL_CONTENT_LOADING = `${COLLECTION_DETAIL}/SET_DETAIL_CONTENT_LOADING`;

// collection -> detail -> activities -> favorite
export const UPDATE_ALL_FAVORITE_LIST = `${COLLECTION_DETAIL}/UPDATE_ALL_FAVORITE_LIST`;
export const UPDATE_GUEST_FAVORITE_LIST = `${COLLECTION_DETAIL}/UPDATE_GUEST_FAVORITE_LIST`;
export const UPDATE_GUEST_LIST_AFTER_DELETE = `${COLLECTION_DETAIL}/UPDATE_GUEST_LIST_AFTER_DELETE`;

// collection -> detail -> settings -> design
export const UPDATE_COLLECTION_NAME_IN_DETAIL = `${COLLECTION_DETAIL}/UPDATE_COLLECTION_NAME_IN_DETAIL`;
export const REPLACE_AUDIO = 'REPLACE_AUDIO';
export const UPDATE_FRAMES = 'UPDATE_FRAMES';
export const UPDATE_AUDIO_REGION = 'UPDATE_AUDIO_REGION';
export const SET_THEME = 'SET_THEME';

export const DELETE_WAVEFORM = 'DELETE_WAVEFORM';
export const CHANGE_TRANSITION = 'CHANGE_TRANSITION';
export const SET_POST_CARD = 'SET_POST_CARD';
