export const CREATE_ELEMENT = 'CREATE_ELEMENT';
export const CREATE_ELEMENTS = 'CREATE_ELEMENTS';

export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';
export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const DELETE_ELEMENTS = 'DELETE_ELEMENTS';
export const DELETE_ALL = 'DELETE_ALL';

export const DELETE_PAGE = 'DELETE_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_PAGES = 'UPDATE_PAGES';
export const CREATE_DUAL_PAGE = 'CREATE_DUAL_PAGE';
export const CREATE_MULTIPLE_DUAL_PAGE = 'CREATE_MULTIPLE_DUAL_PAGE';
export const DELETE_MULTIPLE_PAGE = 'DELETE_MULTIPLE_PAGE';
export const MOVE_PAGE_BEFORE = 'MOVE_PAGE_BEFORE';

export const SET_PAGE_ARRAY = 'SET_PAGE_ARRAY';

export const UPDATE_THEME_PROPERTY = 'UPDATE_THEME_PROPERTY';

export const UPDATE_PAGINATION_TOTAL = 'UPDATE_PAGINATION_TOTAL';
export const SWITCH_SHEET = 'SWITCH_SHEET';

export const SET_PSD_PAGES = 'SET_PSD_PAGES';
