export const BIND_EMAIL_MODAL = 'BIND_EMAIL_MODAL';
export const VIEW_FAVORITE_LIST_MODAL = 'VIEW_FAVORITE_LIST_MODAL';
export const DOWN_LOAD_MSGINFO_MODAL = 'DOWN_LOAD_MSGINFO_MODAL';
export const CHECK_DOWNLOAD_PIN = 'CHECK_DOWNLOAD_PIN';
