export const CURRENT_SET_FAVORITE_IMAGE_COUNT = 'CURRENT_SET_FAVORITE_IMAGE_COUNT';
export const SELECT_IMG_BEFORE_IN_EDITOR = 'SELECT_IMG_BEFORE_IN_EDITOR';
export const SAVE_PRODUCT_INFO_FOR_EDITOR = 'SAVE_PRODUCT_INFO_FOR_EDITOR';
export const CLEAR_PRODUCT_INFO_FOR_EDITOR = 'CLEAR_PRODUCT_INFO_FOR_EDITOR';
export const CLEAR_PROJECT_FOR_EDITOR = 'CLEAR_PROJECT_FOR_EDITOR';
export const API_SUCCESS = 'API_SUCCESS';
