export const ADD_PRESET_MODAL = 'ADD_PRESET_MODAL';
export const RENAME_PRESET_MODAL = 'RENAME_PRESET_MODAL';
export const CREATE_MODAL = 'CREATE_MODAL';
export const EDIT_MODAL = 'EDIT_MODAL';
export const WEBSITE_ALERT_MODAL = 'WEBSITE_ALERT_MODAL';
export const WEBSITE_TEMPLATE_MODAL = 'WEBSITE_TEMPLATE_MODAL';
export const WEBSITE_CUSTOM_MODAL = 'WEBSITE_CUSTOM_MODAL';
